TD-65: Build impl
valitydev/java-shared-resources pull request #2
Opened 2022-01-18 16:04 UTC by echerniak

2022-01-20 08:25 UTC, tolkonepiu requested changes

2022-01-20 08:25 UTC, tolkonepiu commented on src/main/resources/Dockerfile
> +FROM @dockerfile.registry@/openjdk/15-jdk-slim
Пора убирать эту часть:
@dockerfile.registry@
, плюс захватить MAINTAINER, он уже deprecated

2022-01-20 12:46 UTC, vulnbe commented on src/main/resources/Dockerfile
>  COPY @artifactId@-@version@.jar /opt/@artifactId@/@artifactId@.jar
```suggestion
RUN useradd -s /bin/false -U -u 20000 vality

COPY --chown=vality:vality @artifactId@-@version@.jar /opt/@artifactId@/@artifactId@.jar

USER vality:vality
```

2022-01-20 12:46 UTC, vulnbe commented on src/main/resources/Dockerfile
>  COPY @artifactId@-@version@.jar /opt/@artifactId@/@artifactId@.jar
@tolkonepiu Но не факт, что это взлетит

2022-01-21 08:26 UTC, echerniak commented on src/main/resources/Dockerfile
>  COPY @artifactId@-@version@.jar /opt/@artifactId@/@artifactId@.jar
Локально собрал такой образ, приложение внутри без проблем стартануло

2022-01-21 08:59 UTC, vulnbe approved these changes, later dismissed
Надо будет учесть изменения владельца для volumes в k8s

2022-01-21 13:34 UTC, tolkonepiu requested changes

2022-01-21 13:34 UTC, tolkonepiu commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> +                        "application": "@artifactId@"
Давай избавимся, сейчас бесполезно и только дает такой спецэффект
<img width="675" alt="Screenshot 2022-01-21 at 16 33 43" src="https://user-images.githubusercontent.com/5084395/150535827-f38e7a1a-08d1-41d7-a219-f79f03ffcba2.png">

2022-01-21 13:35 UTC, tolkonepiu commented
> Надо будет учесть изменения владельца для volumes в k8s

Призову @vilorij, чтоб тоже поглядел

2022-01-21 13:46 UTC, tolkonepiu requested changes

2022-01-21 13:46 UTC, tolkonepiu commented on .github/workflows/build.yml
> +name: Build Artifact
Надо сразу билды заюзать, у @vitaxa запросить набор

2022-01-21 13:50 UTC, tolkonepiu commented on src/main/resources/logback-spring.xml
>      <property name="LOG_FILE"
Этот параметр тогда тоже не нужен теперь

2022-01-21 13:52 UTC, tolkonepiu commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> +    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">>
Насколько критично локально смотреть на такие логи? Это не усложнит разработку в целом?

2022-01-21 13:52 UTC, tolkonepiu commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> +    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">>
```suggestion
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
```

2022-01-21 13:54 UTC, tolkonepiu commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> +    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">>
Можешь пример билда вбросить?

2022-01-21 14:09 UTC, echerniak commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> +    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">>
На мой взгляд смотреть менее удобно, но при желании разобраться можно. Да и никто не мешает переопределить локально logback.xml
`{"thread_name":"main","message":"ExitState converter. Exit state model: ExitStateModelImpl(super=ExitStateModel(errorCode=null, errorMessage=null, nextState=AdapterState(step=PAYOUT, maxTimePoolingMillis=null, trxInfo=TransactionInfo(trxId=39f6c647-a489-43b7-98c2-a48b76057bdd, trxExtra={}), pollingInfo=null), entryStateModel=EntryStateModelImpl(super=EntryStateModel(withdrawalId=6cd236cc-9790-4de1-9005-32dc4d386cd1, amount=-1391378306, currencyCode=JPY, state=AdapterState(step=PAYOUT, maxTimePoolingMillis=null, trxInfo=null, pollingInfo=null)), customerEmail=customer@test.com)))","@version":"1","logger_name":"com.empayre.adapter.payout.sticpay.converter.exit.ExitToProcessResultConverterImpl","@timestamp":"2022-01-21T14:04:17.440Z","@severity":"INFO"}
`

2022-01-21 14:18 UTC, echerniak commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> +                        "application": "@artifactId@"
Убрал

2022-01-21 14:49 UTC, tolkonepiu commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> +    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">>
Ну ладно, обычный всегда вернуть можно)

2022-01-21 14:49 UTC, tolkonepiu approved these changes

2022-01-21 15:28 UTC, vilorij commented on src/main/resources/Dockerfile
> +USER vality:vality
Вот это имеется ввиду здесь отследить изменение владельца?

Я не очень понимаю, что здесь происходит, но полагаю это шареные билды для ява сервисов.
Прямых волумов явасервисы вроде не маунтят в кубере, но как какой-нибудь соберется, я поэкспериментирую. В чартах есть возможность и менять runas юзера, и ставить права примаунченых файлов и директорий.

2022-01-24 08:04 UTC, echerniak commented on src/main/resources/Dockerfile
> +USER vality:vality
да, здесь изменился владелец для будущих сборок на основе этого образа

2022-01-24 08:04 UTC, merged