add stdout appender, refactor
valitydev/java-shared-resources pull request #7
Opened 2022-02-18 13:28 UTC by karleowne

2022-02-18 13:36 UTC, karleowne commented on src/main/resources/dev/vality/sharedresources/logback/stdout-appender.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
мы же можем занести этот STDOUT аппендер в либу? он используется как дефолтный в k8s 

если занесем , то сможем отрефакторить джавовские чарты и убрать duplicate код их них
```
  - name: config-volume
    mountPath: /opt/***/logback.xml
    subPath: logback.xml
    readOnly: true
  - name: config-volume
    mountPath: /opt/***/loggers.xml
    subPath: loggers.xml
    readOnly: true
```

2022-02-18 13:36 UTC, karleowne commented on src/main/resources/dev/vality/sharedresources/logback/stdout-appender.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
при этом если отдельному сервису нужен специфиный logback.xml то его можно будет переопределить

2022-02-18 13:36 UTC, karleowne commented on src/main/resources/dev/vality/sharedresources/logback/stdout-appender.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
и еще вопрос, у нас же в кластере используется stdout аппендер? судя по логу эластика - да
![image](https://user-images.githubusercontent.com/19729841/154692522-a2f35ec8-84f2-4c44-a1c9-2ff41b54e8be.png)

но где тогда переопределяется с CONSOLE на STDOUT?

2022-02-18 13:46 UTC, tolkonepiu commented on src/main/resources/dev/vality/sharedresources/logback/stdout-appender.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
> у нас же в кластере используется stdout аппендер? судя по логу эластика - да
Это параметр не аппендера, это указание, откуда берет логи filebeat. Такой де параметр есть и у эрланговых сервисов:
https://kibana.empayre.com/app/discover#/doc/filebeat-rbkmoney-processing/filebeat-rbkmoney-processing-2022.02.18-000174?id=UVQUDX8BwijHVn8cbv4-

Аппентер CONSOLE как раз пишет в stdout

2022-02-18 13:46 UTC, karleowne commented on pom.xml
> +    <version>1.0.1</version>
можно кстати сюда занести дефолтные параметры для jar ?
```
   -Xms256m
       -Xmx256m
       -XX:OnOutOfMemoryError="kill -9 %p"
       -XX:+HeapDumpOnOutOfMemoryError
``

2022-02-18 13:47 UTC, tolkonepiu commented on src/main/resources/dev/vality/sharedresources/logback/stdout-appender.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
> мы же можем занести этот STDOUT аппендер в либу? он используется как дефолтный в k8s

можем, если у нас там действительно дублируется конфигурация

2022-02-18 13:47 UTC, tolkonepiu commented on src/main/resources/dev/vality/sharedresources/logback/stdout-appender.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
> если занесем , то сможем отрефакторить джавовские чарты и убрать duplicate код их них

тут только за, лучше, чтоб конфигурация логов была здесь

2022-02-18 13:48 UTC, karleowne commented on src/main/resources/dev/vality/sharedresources/logback/stdout-appender.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
вот чтоб эту часть кода выпилить https://github.com/empayre/cloud-infra/pull/254/files#r806284306

2022-02-18 14:00 UTC, karle0wne commented on src/main/resources/dev/vality/sharedresources/logback/stdout-appender.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
> Аппентер CONSOLE как раз пишет в stdout

если filebeat берет логи от CONSOLE тогда у нас тогда все что нужно в этой либе и так есть, а logback.xml  из клауд инфра не  используется.  

 данный файл который я добавил здесь [stdout-appender.xml](https://github.com/valitydev/java-shared-resources/pull/7/files#diff-2d9305d47f8330968a8ae3ac44c24bf6962d267d78b3ef02f773288122dccea0)  является дефолтным в инфре https://github.com/empayre/cloud-infra/blob/master/helmfile/config/logs/logback.xml 
но при этом, файл из инфры ничем не отличается от  [console-appender.xml](https://github.com/valitydev/java-shared-resources/blob/master/src/main/resources/dev/vality/sharedresources/logback/console-appender.xml) из либы . только словом STDOUT вместо CONSOLE , поэтому я подумал что надо доп файл в эту либу добавить

2022-02-21 02:53 UTC, vilorij commented on src/main/resources/dev/vality/sharedresources/logback/stdout-appender.xml
> +    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
*мимопроходил* Filebeat просто читает json простыню лога контейнера, который пишется в формате докера, и в этом файле есть разбивка по стримам, куда в контейнере прилетела запись - stream: stdout, stream: stderr. На скрине просто отображение этой мета инфы, которой файлбит донасыщает логи, посылаемые в эластик.

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/Dockerfile
> +CMD ["java", "-jar","/opt/@artifactId@/@artifactId@.jar"]
переносим управление jvm options на уровень k8s

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +    <appender name="COLOR_CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
![image](https://user-images.githubusercontent.com/19729841/154984097-81820243-59a9-45a3-85de-afe3e3702cd7.png)

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +    <appender name="DEFAULT_CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
![image](https://user-images.githubusercontent.com/19729841/154984153-2af476e5-e52f-4105-8062-414952436106.png)

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +    <appender name="JSON_K8S_CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
![image](https://user-images.githubusercontent.com/19729841/154984195-fc1304cb-a3a3-4728-b854-3e5534a85997.png)

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +    <logger name="${loggerNameSpringApplicationWoody}" level="${loggingLevelSpringApplicationWoody}"/>
параметризуем логгеры чтобы можно было на уровне кластера менять пакет и дефолтный левел для него
например
```yaml
logging:
  level:
    spring-application-root: info
    spring-application-woody: error
logger:
  name:
    spring-application-root: com.empayre
#    spring-application-root: dev.vality.magista
    spring-application-woody: dev.vality.woody
#    spring-application-woody: com.rbkmoney.woody для не бампаных сервисов
```

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +                        <appender-ref ref="DEFAULT_CONSOLE"/>
данная инициализация рутового апендера решает проблему когда при запуске приложения лог в json.

по умолчанию используется `ref="COLOR_CONSOLE"` , на уровне k8s этот параметр будет переопределяться в `application.yml`
```yaml
logback:
  appender: JSON_K8S_CONSOLE # возможные значения: DEFAULT_CONSOLE || COLOR_CONSOLE || JSON_K8S_CONSOLE
```

в случае если юзер дисмиснул правильное название, то будет использоваться `ref="DEFAULT_CONSOLE"` с дефолтным спринговым выводом

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +                    <pattern>${loggerPatternSpringApplicationJsonK8sConsole}</pattern>
этот параметр будет переопределяться (если нужно например добавить новых полей в определенном сервисе) в `application.yml`
```yaml
logging:
  pattern:
    spring-application-json-k8s-console: >-
      {
        "@timestamp": "%date{yyy-MM-dd'T'HH:mm:ss.SSSXXX, UTC}",
        "@severity": "%level",
        "thread_name": "%thread",
        "application": "${spring.application.name}",
        "logger_name": "%logger",
        "method": "%method",
        "line": "%line",
        "message": "%message"
```

чтоб добавить поле `asd` в вывод лога
```yaml
logging:
  pattern:
    spring-application-json-k8s-console: >-
      {
        "asd": "${asd}"
```

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +                    <pattern>${loggerPatternSpringApplicationJsonK8sConsole}</pattern>
при это если устраивает формат текущий формат, который идет как дефолтный 
```yaml
    spring-application-json-k8s-console: >-
      {
        "@timestamp": "%date{yyy-MM-dd'T'HH:mm:ss.SSSXXX, UTC}",
        "@severity": "%level",
        "thread_name": "%thread",
        "application": "${spring.application.name}",
        "logger_name": "%logger",
        "method": "%method",
        "line": "%line",
        "message": "%message"
      }
```
то переопределять ничего не потребуется

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +                        <exclude>^net\.sf\.cglib\.proxy\.MethodProxy\.invoke</exclude>
немного поменял stackTrace , добавил исключение из него данных invoke + ограничение по размеру

2022-02-21 15:39 UTC, karleowne commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> -                <context/>
в обновленном паттерне дропнул mdc, context, version как юзлесные для файлбит и локали поля

2022-02-21 15:39 UTC, karleowne commented on README.md
> +    spring-application-woody: dev.vality.woody
любые из этих параметров можно заюзать в k8s или для локального переопределения

2022-02-21 15:43 UTC, karleowne commented on README.md
> +        "line": "%line",
эти 2 параметра добавил как дефолтные для вывода , не лишние

2022-02-21 17:04 UTC, tolkonepiu requested changes

2022-02-21 17:04 UTC, tolkonepiu commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> -                <context/>
mdc не юзелес

2022-02-21 17:05 UTC, tolkonepiu requested changes

2022-02-21 17:05 UTC, tolkonepiu commented on README.md
> +        "asd": "asd",
А для чего понадобятся такие кастомы?

2022-02-21 17:30 UTC, karleowne commented on README.md
> +        "asd": "asd",
Если для отдельного сервиса требуется переопределить поля которые выводятся в консоль (добавить дополнительные) 

Но дефолтный параметр настроен на вывод вссех текущих полей, так что его дергать не потребуется (только завтра еще верну mds) "но мало ли что" , вдруг понадобится. 

Допустим был прецедент , что бы на уровне конфигов кластера добавляли проперти application которого в этой либе нет

В целом снаружи данные изменение ничего не меняют , только добавляется больше параметризации для управления на уровне отдельных чартов . Для сервисов и либ (+woody) у нас щас юзается куча пакетов - dev.vality, com.empayre , com.rbkmoney ; в чартах щас это через раз учитывается. С этими добавлчемыми параметрами это будет частью описания aplication.yml который будет как настройка values в чарте

2022-02-22 06:19 UTC, karleowne commented on README.md
> +        "asd": "asd",
+ удобство в том, что не нужно вводить дополнительные файлы в кластере конфигов (logback.xml) , переопределять с нуля, все решается парой строчек в application.yml

2022-02-22 06:28 UTC, karleowne commented on src/main/resources/dev/vality/sharedresources/logback/console-appender.xml
> -                <context/>
вернул

2022-02-22 08:16 UTC, tolkonepiu requested changes

2022-02-22 08:16 UTC, tolkonepiu commented on src/main/resources/logback-spring.xml
> +    <logger name="${loggerNameSpringApplicationWoody}" level="${loggingLevelSpringApplicationWoody}"/>
Выглядит так, что это вообще можно удалить. Никогда не использовалось, а так выглядит странно.

2022-02-22 08:16 UTC, tolkonepiu commented on src/main/resources/logback-spring.xml
> +    <springProperty scope="context" name="loggerPatternSpringApplicationJsonK8sConsole" source="logging.pattern.spring-application-json-k8s-console" defaultValue="{&quot;@timestamp&quot;: &quot;%date
Не совсем нравится, что основная конфигурация спрятана в одной строке. Подозреваю, что связано из-за гибкости при конфигурации, которая кажется и не нужна.

2022-02-22 08:17 UTC, tolkonepiu commented on README.md
> +        "asd": "asd",
> что бы на уровне конфигов кластера добавляли проперти application

Он был тут, в итоге пильнули отсюда лишнее.

2022-02-22 08:21 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +    <logger name="${loggerNameSpringApplicationWoody}" level="${loggingLevelSpringApplicationWoody}"/>
нам тут не обязательно выставлять `<logger name="dev.vality" level="INFO"/>` ?

2022-02-22 08:29 UTC, karleowne commented on src/main/resources/logback-spring.xml
> +    <logger name="${loggerNameSpringApplicationWoody}" level="${loggingLevelSpringApplicationWoody}"/>
но в целом конечно это можно делать и через
```yaml
logging:
  level:
    dev:
      vality: info
```

2022-02-22 09:04 UTC, tolkonepiu commented on src/main/resources/logback-spring.xml
> +                            "application": "${springApplicationName}",
Это можно выпилить, ненужный тег

2022-02-22 09:04 UTC, tolkonepiu commented on src/main/resources/logback-spring.xml
> +                            "method": "%method",
А подскажи, что такое method и line?

2022-02-22 09:04 UTC, tolkonepiu commented on src/main/resources/logback-spring.xml
> +                            "commit_id": "@git.commit.id.abbrev@",
Тоже не нужно

2022-02-22 09:08 UTC, tolkonepiu commented on src/main/resources/logback-spring.xml
> +                            "method": "%method",
а, я понял. Кажется, как будто лишнее, это же будет в тегах у json.

2022-02-22 09:34 UTC, karleowne commented
@tolkonepiu 
по поводу параметров вывода
щас вывод выглядит так 
![image](https://user-images.githubusercontent.com/19729841/155103424-85e69f20-15d2-4a96-b380-a92bd2f37446.png)


строка
```json
{
  "@timestamp": "2022-02-22T09:31:04.497Z",
  "@severity": "INFO",
  "thread_name": "main",
  "application": "app",
  "commit_id": "a1e962a",
  "logger_name": "org.springframework.boot.web.embedded.tomcat.TomcatWebServer",
  "method": "start",
  "line": "220",
  "message": "Tomcat started on port(s): 8023 (http) with context path ''"
}
```

тут хочется понять, почему параметры , которые ты перечислил выше не нужны:
1)
```json
{
 "application": "app",
}
```
этот параметр у нас щас используется как самый популярный в кибане, основной разделитель для сервиса
![image](https://user-images.githubusercontent.com/19729841/155102683-2afdb271-e2d6-440f-ace9-f13828aff7d0.png)

2)
```json
{
 "commit_id": "a1e962a",
}
```

этот мне кажется можно включить, тк фильтрация по этому параметру позволит фильтровать логи в разрезе последней выкатки 

3) 
```json
{
  "method": "start",
  "line": "220",
}
```
 тут конечно не уверен, но возможно наличие информации о названии метода  и номера строки может помочь при разборе инцидентов при поиске конкретного участка кода с проблемой

2022-02-22 10:20 UTC, vilorij commented
application - может популярный, но не универсальный между явой, эрлангом и инфрой.

Универсальные
kubernetes.labels.app_kubernetes_io/name | payouter
kubernetes.labels.selector_cilium/release | payouter

В кибане заведен алиас для универсального - service, по которому можно искать

О коммите есть инфа в кубере:
kubernetes.container.image | docker.io/rbkmoney/payouter:a0e37ad47ee5563008d2af47c58a9f117e941db0

2022-02-22 11:52 UTC, tolkonepiu commented
> этот параметр у нас щас используется как самый популярный в кибане, основной разделитель для сервиса

Не используется, мы используем либо service (alias на универсальные), либо универсальные теги кубера.

> этот мне кажется можно включить, тк фильтрация по этому параметру позволит фильтровать логи в разрезе последней выкатки

У нас уже есть `kubernetes.container.image`, не вижу особого смысла плодить лишние, специфичные под язык, теги

> тут конечно не уверен, но возможно наличие информации о названии метода и номера строки может помочь при разборе инцидентов при поиске конкретного участка кода с проблемой

Сомневаюсь, разбивка на такие теги будет полезна только для фильтрации и поиска чего либо. В данном случае method и line будут неиспользуемыми. В целом и так есть logger name, который скажет, где именно писали лог например.

2022-02-22 12:38 UTC, tolkonepiu commented on src/main/resources/Dockerfile
> +CMD ["java", "-jar","/opt/@artifactId@/@artifactId@.jar"]
Давай уберем еще самую первую строку
```
# @dockerfile.Template@
```

2022-02-22 12:41 UTC, tolkonepiu approved these changes

2022-02-22 12:45 UTC, merged